version: "3"
services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: shoppinglist_db
            POSTGRES_USER: dlugi
            POSTGRES_PASSWORD: test_pass_123
        env_file:
            - ./.env.prod
        volumes:
            - pgdata:/var/lib/postgresql/data
    api:
        build:
            context: .
        ports:
            - "8000:8000"
            - "5432:5432"
            # - "25:25"
        env_file:
            - ./.env.prod
        volumes:
            - ./:/shoppinglist
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
    smtp4dev:
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            - "5000:80"
            - "25:25"
            - "143:143"
        volumes:
            - smtp4dev-data:/smtp4dev
        depends_on:
            - api
    frontend:
        build:
            context: frontend/
        ports:
            - "3000:3000"
        command: npm start
        depends_on:
            - api
volumes:
    pgdata:
    smtp4dev-data:
