# Generated by Django 4.1.4 on 2022-12-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='api.userprofile'),
        ),
    ]
