# Generated by Django 4.1.4 on 2022-12-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_item_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds'),
        ),
    ]
